### ISSUE TITLE
Not working as of April 2019

### ISSUE THREAD

**Issue by darthwalsh** [jeremyBanks/hide-hnq#7]
Not working for me, [somebody else had this issue too](https://meta.stackexchange.com/questions/84389/filtering-hot-questions/272128#comment1066198_272128).

In the chrome debugger on content.js:97, `hnq.querySelector('a.show-more')` is returning null which causes an error:

> content.js:124 TypeError: Cannot read property 'dataset' of null
>     at content.js:97

**Comment by jeremyBanks** [comment]
(Previously replied by email, but for public reference:) I am no longer maintaining this extension, and I no longer use Chrome. I will archive this repo for clarity, but if someone wants to fork and fix, I would be happy to add a notice directing visitors there instead.
